[package]
name = "civ5-p2p"
version = "0.1.0"
authors = ["gak <gak@gak0.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
